services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      PORT: 5000
      CONSTRING: mongodb+srv://s26s2053:admin@qmtcl.q2t60.mongodb.net/qmtDB?retryWrites=true&w=majority&appName=qmtCL
networks:
      app-network:
          driver: bridge
